.TH PFETCH 1
.SH NAME
pfetch \- A pretty system information tool written in POSIX sh
.SH SYNOPSIS
.B pfetch
.RI [ options ]
.SH DESCRIPTION
.B pfetch
A pretty system information tool written in POSIX sh.
.SH OPTIONS
.TP
.BR \-d,\ --debug
Debug information
.TP
.BR \-v,\ --version
Prints out pfetch version
